name: Build and Test Win64
on:
  push:
    branches: [ master, dev, update/202012v2]

  # *** warning *** - be careful if using runners on own infra on public repos with public pull requests
  pull_request:
    branches: [ master, dev, integrate/thingbase, fixes/sonar, fixes/documentation ]


jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      platform: x64
      VCPKG_DEFAULT_TRIPLET: x64-windows
      GENERATOR: "Visual Studio 16 2019"
      ARCH:      "x64"
      CMAKE_TOOLCHAIN_FILE: "C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
      CMAKE_INSTALL_PREFIX: "C:\\install\\nucleus"
      WORKDIR:  "D:\\a\\nucleus\\nucleus\\"
      MSBUILD:  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
    strategy:
      matrix:
        CONFIG: [Debug]
    steps:
      - name: Update PATH
        run: echo "${env:MSBUILD}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Cache vcpkg packages
        uses: actions/cache@v1
        id: cache-vcpkg-packages
        with:
          path: C:/vcpkg/packages
          key:  vcpkg-packages-45e5a67

      - name: Cache vcpkg installed
        uses: actions/cache@v1
        id: cache-vcpkg-installed
        with:
          path: C:/vcpkg/installed
          key:  vcpkg-installed-45e5a67

      - name: Clone the git repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Deps
        run: |
          vcpkg install libpmemobj-cpp:x64-windows
          vcpkg install pmdk:x64-windows
          vcpkg update
          vcpkg upgrade libpmemobj-cpp:x64-windows --no-dry-run
          vcpkg upgrade pmdk:x64-windows --no-dry-run

      - name: install-python-deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install keyring keyrings-alt requests
          python -m pip list

      - name: vcpkg integrate install
        run: vcpkg integrate install

      - name: Configure
        run: cmake . -Bbuild
          -G "${env:GENERATOR}"
          -A "${env:ARCH}"
          -DCMAKE_TOOLCHAIN_FILE="${env:CMAKE_TOOLCHAIN_FILE}"
          -DCMAKE_INSTALL_PREFIX="${env:CMAKE_INSTALL_PREFIX}"

      - name: Build
        run: msbuild build/ALL_BUILD.vcxproj /property:Configuration=${{ matrix.CONFIG }} /verbosity:minimal /m

      - name: Tests
        working-directory: build
        run: ctest -C ${{ matrix.CONFIG }} --output-on-failure --timeout 540
